[package]
name = "ow2_pubsub_broker"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.0"
actix-web = "4.3.1"
actix-web-actors = "4.2.0"
env_logger = "0.10.0"
log = "0.4.17"
rand = "0.8.5"
