max_width = 80
array_width = 80
chain_width = 80
reorder_impl_items = true
use_small_heuristics = "Max"
format_macro_matchers = true
inline_attribute_width = 80
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
newline_style = "Unix"
condense_wildcard_suffixes = true
comment_width = 80
wrap_comments = true
normalize_comments = true
